imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
    config:
        contentsCss: "EXT:gf_sitepackage/Resources/Public/Css/rte.css"

        stylesSet:
            - { name: "Button: Primary", element: "a", attributes: { class: "btn btn-primary" } }
            - { name: "Button: Secondary", element: "a", attributes: { class: "btn btn-secondary" } }
            - { name: "Button: Success", element: "a", attributes: { class: "btn btn-success" } }
            - { name: "Button: Danger", element: "a", attributes: { class: "btn btn-danger" } }
            - { name: "Button: Warning", element: "a", attributes: { class: "btn btn-warning" } }
            - { name: "Button: Info", element: "a", attributes: { class: "btn btn-info" } }
            - { name: "Button: Light", element: "a", attributes: { class: "btn btn-light" } }
            - { name: "Button: Dark", element: "a", attributes: { class: "btn btn-dark" } }
            - { name: "Button: Link", element: "a", attributes: { class: "btn btn-link" } }
            - { name: "Font size 1", element: "p", attributes: { class: "fs-1" } }
            - { name: "Font size 2", element: "p", attributes: { class: "fs-2" } }
            - { name: "Font size 3", element: "p", attributes: { class: "fs-3" } }
            - { name: "Font size 4", element: "p", attributes: { class: "fs-4" } }
            - { name: "Font size 5", element: "p", attributes: { class: "fs-5" } }
            - { name: "Line height 1", element: "p", attributes: { class: "lh-1" } }
            - { name: "Line height small", element: "p", attributes: { class: "lh-sm" } }
            - { name: "Line height base", element: "p", attributes: { class: "lh-base" } }
            - { name: "Line height large", element: "p", attributes: { class: "lh-lg" } }

        toolbarGroups:
            - { name: styles, groups: [ format, styles ] }
            - { name: basicstyles, groups: [ basicstyles ] }
            - { name: paragraph, groups: [ list, indent, blocks, align ] }
            - "/"
            - { name: links, groups: [ links ] }
            - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
            - { name: editing, groups: [ spellchecker ] }
            - { name: insert, groups: [ insert ] }
            - { name: tools, groups: [ table, specialchar ] }
            - { name: document, groups: [ mode ] }

        format_tags: "p;h1;h2;h3;h4;h5;h6;pre"

        justifyClasses:
            - text-start
            - text-center
            - text-end
            - text-justify

        extraPlugins:
            - justify

        removePlugins:
            - image

        removeButtons:
            - Anchor
            - Underline
            - Strike
